"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
// @ts-ignore
import { PersistGate } from "redux-persist/integration/react";  // エラーが出るため、@ts-ignore
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { Toaster } from "react-hot-toast";

import { AppProvider } from "@/context/AppContext";
import { persistor, store } from "./store";
import Header from "@/components/layout/header/Header";
import Sidebar from "@/components/layout/sidebar/Sidebar";
import { RegisterModal } from "@/features/modal/RegisterModal";
import { LoginModal } from "@/features/modal/LoginModal";
import { LogoutModal } from "@/features/modal/LogoutModal";
import { EditProfileModal } from "@/features/modal/EditProfileModal";
import { DeleteAccountModal } from "@/features/modal/DeleteAccountModal";
import { DeletePostOrCommentConfirmModal } from "@/features/modal/DeletePostOrCommentConfirmModal";
import { PostModal } from "@/features/modal/PostModal";
import { ConfirmModal } from "@/features/modal/ConfirmModal";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Code X",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <SessionProvider session={session}>
            <Provider store={store}>
              <PersistGate loading={null} persistor={persistor}>
                <Toaster />
                <RegisterModal />
                <LoginModal />
                <LogoutModal />
                <EditProfileModal />
                <DeleteAccountModal />
                <DeletePostOrCommentConfirmModal />
                <PostModal />
                <ConfirmModal />
                <div className="flex lg:mx-4">
                  <div className="sticky top-0 w-20 max-w-20 lg:w-64 lg:max-w-64 h-screen">
                    <Header />
                  </div>
                  <div className="w-[calc(100%-96px)] max-w-[calc(100%-96px)] lg:w-[calc(100%-560px)] lg:max-w-[calc(100%-560px)] min-h-screen border-x border-gray-600">
                    {children}
                  </div>
                  <div className="hidden lg:block sticky top-0 w-96 max-w-96 min-w-60 h-screen hover:overflow-x-hidden hover:overflow-y-auto">
                    <Sidebar />
                  </div>
                </div>
              </PersistGate>
            </Provider>
          </SessionProvider>
        </AppProvider>
      </body>
    </html>
  );
};
